baseURL = 'https://ydjemmada.github.io/'
languageCode = 'en-us'
title = 'YAHIA DJEMMADA'
theme = 'researcher'

enableEmoji = true
googleAnalytics = 'G-BLPCZY56GF'

[params]
    defaultTheme = "auto"
    # ProfileMode is disabled because we are using a custom layouts/index.html
    [params.profileMode]
        enabled = false

    [[params.socialIcons]]
        name = "email"
        url = "mailto:yahia.djemmada@nhsm.edu.dz"

[menu]
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/publications"
    weight = 1
  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/CMaterials"
    weight = 2
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true
