baseurl = 'https://ydjemmada.github.io/'
title = 'YAHIA DJEMMADA'
theme = 'researcher'
relativeURLs = true
canonifyURLs = true

# Disable certain content types (taxonomy and term)
disableKinds = ['taxonomy', 'term']

# Enable emoji support and disable KaTeX globally
enableEmoji = true
math = false  # Disable KaTeX globally (set true to enable KaTeX)

# Google Analytics tracking ID
googleAnalytics = 'G-BLPCZY56GF'

# Custom parameters for site appearance and settings
[params]
  author = 'YAHIA DJEMMADA'
  description = '#'
  favicon = 'favicon.ico'  # Path to a favicon.ico for the site
  logo = 'avatar.png'  # Path or URL to the logo image for the header
  
  # Footer settings
  #[params.footer]
   # text = 'By Yahia Djemmada'
   # url = 'https://ydjemmada.github.io/'
   # imgurl = '/logo.png'  # URL or path to an image to appear in the footer
  
  # Style settings (can be omitted if not needed)
  [params.style]  
    fontFamily = 'Inconsolata'  # Font family for the site
    fontSize = '14pt'  # Font size for the site
    pageWidth = '750px'  # Width of the content area
    avatarSize = '90px'  # Avatar size for user profile
    colorBlack = '#222222'  # Primary color for black text
    colorRed = '#dc3545'  # Primary color for red accents

  # Social media links (icons for social media in the header/footer)
  [[params.socialIcons]]
    icon = 'fas fa-envelope'
    title = 'E-mail'
    url = 'mailto:yahia.djemmada@nhsm.edu.dz'

  [[params.socialIcons]]
    icon = 'fab fa-telegram'
    title = 'Telegram'
    url = 'https://t.me/mathxro'

# Permalink configuration for your pages
[permalinks]
  '/' = '/:filename'  # Use filename for the homepage URL

# Main menu configuration
[menu]
  [[menu.main]]
    name = 'About Me'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'Contact'
    url = '/contact'
    weight = 3

  [[menu.main]]
    name = 'Resources'
    url = '/CMaterials'
    weight = 2

# Markdown rendering settings
[markup.goldmark.renderer]
  unsafe = true  # Allow raw HTML in markdown files
